### ISSUE TITLE
any method to support one to many relation

### ISSUE THREAD

**Issue by sdhjl2000** [dotarj/Dapper.Mapper#1]
could it be possible to support one to many mapping

**Comment by brugner** [comment]
This is dead, isn't it?

**Comment by dotarj** [comment]
@n6ither If you mean that the project is dead, then no. If you mean this feature request, then the answer is that I have no intentions of adding one to many support to Dapper.Mapper. One to one mapping is straight forward which makes the library simple. One to many is more complex, for example: how to relate objects, different types of collections.

**Comment by brugner** [comment]
I understand, maybe I could have expressed myself better but, yes, I see your point and I did resolve my problem using a simple mapping aproach. Thank you and kind regards.
