### ISSUE TITLE
Support of QueryMultiple

### ISSUE THREAD

**Issue by ssougnez** [dotarj/Dapper.Mapper#2]
Hello,

Say I have this:

`string sql = "SELECT ...; SELECT ... INNER JOIN ...";`

I would execute this via `connection.QueryMultiple` and then get the different results via `multi.Read`. However, I noticed that in that particular case, "Mapper.Dapper" does not provide a `Read` extension method that would allow me to do something like:

`var obj = multi.Read<T1, T2>();`

In this case, I'm forced to do something like this:

`var obj = multi.Read<T1, T2, T1>((o1, o2) => { o1.Property = o2; return o1; }).ToList();`

**Comment by dotarj** [comment]
A new version of Dapper.Mapper with mapping extension methods for GridReader.Read is now available: [2.0.0](https://github.com/dotarj/Dapper.Mapper/releases/tag/2.0.0). Thank for your suggestion!

**Comment by ssougnez** [comment]
Hi,

I just tested it and it seems to work like a charm, good job ;-)
