### ISSUE TITLE
Three Join - No writable property of type  

### ISSUE THREAD

**Issue by egvrcn** [dotarj/Dapper.Mapper#6]
Hi, i use dapper.mapper. It is so useful.
I want to 3 join mapping. Can i do it with dapper.mapper?

```
string query = @"SELECT      p.*,c.*, s.*
                            FROM            dbo.Product AS p INNER JOIN
                                dbo.Category AS c ON c.CategoryId = p.CategoryId
                            INNER JOIN dbo.Company s ON s.CompanyId = p.CompanyId";

var product = connection.Query<Product, Category, Company>(sql);
```

**Comment by dotarj** [comment]
Hi @egvrcn, this should work given that your Product class has a public writable property Category and Company, for example:

```
public class Product
{
    public Category Category { get; set; }

    public Company Company { get; set; }
}
```

Please let me know if this works, and if not, could you provide some more details?

**Comment by egvrcn** [comment]
Hi @dotarj , thanks for your answer. I forgot add Company. My fault.
Does your dapper.mapper have a number limit about join?
For example, Can I make five different table join with dapper.mapper?

**Comment by dotarj** [comment]
No problem.

Dapper.Mapper supports up to seven types, just like Dapper itself.
